"""Add partener models

Revision ID: 575a23229ebc
Revises: 77512852c863
Create Date: 2026-09-04 08:48:13.297582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575a23229ebc'
down_revision: Union[str, Sequence[str], None] = '77512852c863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_name', sa.String(length=128), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_api_keys')
    # ### end Alembic commands ###
