"""add missing indexes for query patterns


Revision ID: e3ac0bcd181a
Revises: 575a23229ebc
Create Date: 2026-10-02 08:53:44.165736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ac0bcd181a'
down_revision: Union[str, Sequence[str], None] = '575a23229ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_status_starts_at_id', 'events', ['status', 'starts_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_status_starts_at_id', table_name='events')
    # ### end Alembic commands ###
